export const movies = [
    {
        title: "Queen of Tears",
        img: "movie-1.jpg",
        year: "2024",
        cast: "Vice Ganda, Vic Sotto, Jose Manalo, Coco Martin",
        genre: "Action, Drama",
        rating: 10,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis eligendi a doloremque libero. Nulla, odit.",
        type: "Positive",
        duration: "2hr 45m",
        grouping: "asian",
    },

    {
        title: "Captain America - The Winter Soldier",
        img: "movie-2.jpg",
        year: "2019",
        cast: "Vice Ganda, Vic Sotto, Jose Manalo, Coco Martin",
        genre: "Action, Drama",
        rating: 9,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis eligendi a doloremque libero. Nulla, odit.",
        type: "Positive",
        duration: "2hr 45m",
        grouping: "trending",
    },

    {
        title: "Skyfall",
        img: "movie-3.jpg",
        year: "2017",
        cast: "Vice Ganda, Vic Sotto, Jose Manalo, Coco Martin",
        genre: "Action, Drama",
        rating: 8,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis eligendi a doloremque libero. Nulla, odit.",
        type: "Positive",
        duration: "2hr 45m",
        grouping: "asian",
    },

    {
        title: "Interstellar",
        img: "movie-4.jpg",
        year: "2010",
        cast: "Vice Ganda, Vic Sotto, Jose Manalo, Coco Martin",
        genre: "Sci-fi, Drama",
        rating: 8,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis eligendi a doloremque libero. Nulla, odit.",
        type: "Emotional",
        duration: "1hr 45m",
        grouping: "asian",
    },

    {
        title: "Looper",
        img: "movie-5.jpg",
        year: "2024",
        cast: "Vice Ganda, Vic Sotto, Jose Manalo, Coco Martin",
        genre: "Sci-fi, Drama",
        rating: 7,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis eligendi a doloremque libero. Nulla, odit.",
        type: "Positive",
        duration: "2hr 45m",
        grouping: "trending",
    },

    {
        title: "Land of Mine",
        img: "movie-6.jpg",
        year: "2024",
        cast: "Vice Ganda, Vic Sotto, Jose Manalo, Coco Martin",
        genre: "Sci-fi, Drama, War",
        rating: 11,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis eligendi a doloremque libero. Nulla, odit.",
        type: "War",
        duration: "3hr 45m",
        grouping: "trending",
    },

    {
        title: "Queen of Tears",
        img: "movie-1.jpg",
        year: "2024",
        cast: "Vice Ganda, Vic Sotto, Jose Manalo, Coco Martin",
        genre: "Action, Drama",
        rating: 10,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis eligendi a doloremque libero. Nulla, odit.",
        type: "Positive",
        duration: "2hr 45m",
        grouping: "asian",
    },

    {
        title: "Captain America - The Winter Soldier",
        img: "movie-2.jpg",
        year: "2019",
        cast: "Vice Ganda, Vic Sotto, Jose Manalo, Coco Martin",
        genre: "Action, Drama",
        rating: 9,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis eligendi a doloremque libero. Nulla, odit.",
        type: "Positive",
        duration: "2hr 45m",
        grouping: "trending",
    },

    {
        title: "Skyfall",
        img: "movie-3.jpg",
        year: "2017",
        cast: "Vice Ganda, Vic Sotto, Jose Manalo, Coco Martin",
        genre: "Action, Drama",
        rating: 8,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis eligendi a doloremque libero. Nulla, odit.",
        type: "Positive",
        duration: "2hr 45m",
        grouping: "asian",
    },

    {
        title: "Interstellar",
        img: "movie-4.jpg",
        year: "2010",
        cast: "Vice Ganda, Vic Sotto, Jose Manalo, Coco Martin",
        genre: "Sci-fi, Drama",
        rating: 8,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis eligendi a doloremque libero. Nulla, odit.",
        type: "Emotional",
        duration: "1hr 45m",
        grouping: "asian",
    },

    {
        title: "Looper",
        img: "movie-5.jpg",
        year: "2024",
        cast: "Vice Ganda, Vic Sotto, Jose Manalo, Coco Martin",
        genre: "Sci-fi, Drama",
        rating: 7,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis eligendi a doloremque libero. Nulla, odit.",
        type: "Positive",
        duration: "2hr 45m",
        grouping: "trending",
    },

    {
        title: "Land of Mine",
        img: "movie-6.jpg",
        year: "2024",
        cast: "Vice Ganda, Vic Sotto, Jose Manalo, Coco Martin",
        genre: "Sci-fi, Drama, War",
        rating: 11,
        description: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Officiis eligendi a doloremque libero. Nulla, odit.",
        type: "War",
        duration: "3hr 45m",
        grouping: "trending",
    },

    
]